### ISSUE TITLE
Error applying ddcloud_firewall_rule with source or target address list

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#42]
I have tested the ddcloud_port_list firewall creation and it works without incident.  however, in specifying a couple of combinations of the same using address lists it fails either saying it wants a valid source IP or destination IP.  I have attached the bug report for review.
[Terraform-Debug-20161031.zip](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/files/563073/Terraform-Debug-20161031.zip)

**Comment by tintoy** [comment]
Thanks! Should be fixed in 25bdac4fb9b11ac2beaf8e400478cb439dbcf183.

**Comment by tintoy** [comment]
I'm closing this (should be fixed now), but let me know if you still have problems and I'll reopen it.

**Comment by wninobla** [comment]
Works!  But, the other slight bug is still there as its still trying to modify the child_lists...

**Comment by tintoy** [comment]
Ah, that’s a separate issue - haven’t tackled that one yet. Does it go away if you use the order that Terraform changes them to? If so then at least there’s a workaround. I’ll look into changing it over to a Set sometime tomorrow.

**Comment by wninobla** [comment]
I'll try it out but I haven't changed the lines at all and it wants to modify them each time.  I do recall its changing it in the same order so maybe moving it around will do.  I'll give it a whirl when I get a chance.

**Comment by wninobla** [comment]
OK I changed the order and it does flag it as “no changes” in terraform.  Strange indeed.  On that note, if I change the ordering of the list it resolves just fine it seems.  I went from:

resource "ddcloud_port_list" "web-services-list" {
  name                 = "WEB_Services_List"
  description          = "Port group for all HTTP/HTTPS traffic"

  child_lists          = [
    "${ddcloud_port_list.http-list.id}",
    "${ddcloud_port_list.http-alt-list.id}",
    "${ddcloud_port_list.https-list.id}",
  ]

  networkdomain        = "${ddcloud_networkdomain.networkdomain.id}"
  depends_on           = ["ddcloud_networkdomain.networkdomain"]
}

To:

resource "ddcloud_port_list" "web-services-list" {
  name                 = "WEB_Services_List"
  description          = "Port group for all HTTP/HTTPS traffic"

  child_lists          = [
    "${ddcloud_port_list.https-list.id}",
    "${ddcloud_port_list.http-alt-list.id}",
    "${ddcloud_port_list.http-list.id}",
  ]

  networkdomain        = "${ddcloud_networkdomain.networkdomain.id}"
  depends_on           = ["ddcloud_networkdomain.networkdomain"]
}

It’s almost like it reads say http and once something else comes along it gets foo barred namely https…
